### ISSUE TITLE
Boost/resim plans

### ISSUE THREAD

**Issue by LDClark** [x2sky/Esapi_AddSetupBeams#3]
Do you know if you can make this work on plans that have already been treated and copied?  If you add a setup field in Eclipse, it copies the couch parameters to the setup field.  If a plan is added in scripting, I think the default is to add the default couch parameters.  Then it is not treatable as the vrt/lng/lat are different.

**Comment by x2sky** [comment]
Well, this is not something that's available in scripting now...
The method just doesn't allow us to put couch position:
public Beam AddSetupBeam(
	ExternalBeamMachineParameters machineParameters,
	VRect<double> jawPositions,
	double collimatorAngle,
	double gantryAngle,
	double patientSupportAngle,
	VVector isocenter
)
In fact couch position is not even gettable.

Other things like tolerance table is gettable but non-editable:
public string ToleranceTableLabel { get; }
